# ==========================================================
# CONFIG CLASH VERGE WINDOWS - FULLY FIXED & OPTIMIZED
# ==========================================================
port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
ipv6: true

# DNS Detail & Optimalisasi Fake-IP
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.apple.com
    - ntp.*.com
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - stun.l.google.com
    - "+.nflxvideo.net"
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
  fallback:
    - 1.1.1.1
    - 8.8.8.8

# TUN Mode Desktop App Kompatibilitas
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true

# ==========================================================
# DETAILED RULE PROVIDERS
# ==========================================================
rule-providers:
  rule_Direct:
    type: http
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_direct.yaml
    interval: 86400
  rule_umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_umum.yaml
    interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_portgames.yaml
    interval: 86400
  rule_videoconferences:
    type: http
    behavior: classical
    path: "./rule_provider/rule_videoconferences.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_videoconferences.yaml
    interval: 86400
  rule_Indo:
    type: http
    behavior: classical
    path: "./rule_provider/rule_indo.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_indo.yaml
    interval: 86400
  rule_Sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_sosmed.yaml
    interval: 86400
  rule_Streaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_streaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_streaming.yaml
    interval: 86400
  rule_Gaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_gaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_gaming.yaml
    interval: 86400
  rule_Speedtest:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_speedtest.yaml
    path: "./rule_provider/rule_speedtest.yaml"
    interval: 86400
  rule_discord:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.yaml
    path: "./rule_provider/rule_discord.yaml"
    interval: 86400
  rule_hijacking:
    type: http
    behavior: classical
    path: "./rule_provider/rule_hijacking.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hijacking.yaml
    interval: 86400
  rule_privacy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_privacy.yaml
    path: "./rule_provider/rule_privacy.yaml"
    interval: 86400
  rule_basicads:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: "./rule_provider/rule_basicads.yaml"
    interval: 43200
  rule_personalads:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_personalads.yaml
    path: "./rule_provider/rule_personalads.yaml"
    interval: 86400
  rule_malicious:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_malicious.yaml
    path: "./rule_provider/rule_malicious.yaml"
    interval: 43200
  rule_maliciousip:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_maliciousip.yaml
    path: "./rule_provider/rule_maliciousip.yaml"
    interval: 43200
  rule_falsepositive:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_falsepositive.yaml
    path: "./rule_provider/rule_falsepositive.yaml"
    interval: 86400
  rule_porn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_porn.yaml
    path: "./rule_provider/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_nsfw.yaml
    path: "./rule_provider/rule_nsfw.yaml"
    interval: 43200
  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_lancidr.yaml
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400
  rule_telegramcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_telegramcidr.yaml
    path: "./rule_provider/rule_telegramcidr.yaml"
    interval: 86400
  rule_telegram:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_telegram.yaml
    path: "./rule_provider/rule_telegram.yaml"
    interval: 86400
  rule_disneyplus:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_disneyplus.yaml
    path: "./rule_provider/rule_disneyplus.yaml"
    interval: 86400
  rule_games:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400
  rule_hbo:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hbo.yaml
    path: "./rule_provider/rule_hbo.yaml"
    interval: 86400
  rule_hboasia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hboasia.yaml
    path: "./rule_provider/rule_hboasia.yaml"
    interval: 86400
  rule_hbohk:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hbohk.yaml
    path: "./rule_provider/rule_hbohk.yaml"
    interval: 86400
  rule_hbousa:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hbousa.yaml
    path: "./rule_provider/rule_hbousa.yaml"
    interval: 86400
  rule_iqiyi:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_iqiyi.yaml
    path: "./rule_provider/rule_iqiyi.yaml"
    interval: 86400
  rule_iqiyiinter:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_iqiyiinter.yaml
    path: "./rule_provider/rule_iqiyiinter.yaml"
    interval: 86400
  rule_line:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_line.yaml
    path: "./rule_provider/rule_line.yaml"
    interval: 86400
  rule_metaverse:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_metaverse.yaml
    path: "./rule_provider/rule_metaverse.yaml"
    interval: 86400
  rule_netflix:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_netflix.yaml
    path: "./rule_provider/rule_netflix.yaml"
    interval: 86400
  rule_primevideo:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_primevideo.yaml
    path: "./rule_provider/rule_primevideo.yaml"
    interval: 86400
  rule_playstore:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_playstore.yaml
    path: "./rule_provider/rule_playstore.yaml"
    interval: 86400
  rule_tiktok:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400
  rule_twitch:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_twitch.yaml
    path: "./rule_provider/rule_twitch.yaml"
    interval: 86400
  rule_twitter:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_twitter.yaml
    path: "./rule_provider/rule_twitter.yaml"
    interval: 86400
  rule_Youtube:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_youtube.yaml
    path: "./rule_provider/rule_youtube.yaml"
    interval: 86400

# ==========================================================
# PROXY PROVIDERS (Remote Files dari GitHub)
# ==========================================================
proxy-providers:
  premium-provider:
    type: http
    # GANTI LINK DI BAWAH DENGAN LINK RAW premium_proxies.yaml ANDA
    url: "https://raw.githubusercontent.com/ikozu/ikozu/refs/heads/main/premium_proxies.yaml"
    path: ./providers/premium_proxies.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  scraping-provider:
    type: http
    # GANTI LINK DI BAWAH DENGAN LINK RAW scraping_proxies.yaml ANDA
    url: "https://raw.githubusercontent.com/ikozu/ikozu/refs/heads/main/scraping_proxies.yaml"
    path: ./providers/scraping_proxies.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

# ==========================================================
# PROXY GROUPS
# ==========================================================
proxy-groups:
  - name: 💎 Premium Account
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 900
    tolerance: 50
    lazy: true
    use:
      - premium-provider

  - name: 👾Scraping Account
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 900
    tolerance: 50
    lazy: true
    use:
      - scraping-provider

  - name: 🤲 BANSOS ⚡ Auto-Ping
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 900
    tolerance: 50
    lazy: true
    use:
      - scraping-provider

  - name: 🚀 Proxy
    type: select
    proxies:
      - 💎 Premium Account
      - 🔮 Load-Balance
      - ⚡ Auto-Ping
      - 👾Scraping Account
      - 🤲 BANSOS ⚡ Auto-Ping
      - DIRECT

  - name: 🔮 Load-Balance
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 900
    strategy: round-robin
    lazy: true
    proxies:
      - 💎 Premium Account
      - 👾Scraping Account

  - name: ⚡ Auto-Ping
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 900
    tolerance: 50
    lazy: true
    proxies:
      - 💎 Premium Account
      - 👾Scraping Account
      - 🤲 BANSOS ⚡ Auto-Ping

# ==========================================================
# RULES MAPPING
# ==========================================================
rules:
  # System & LAN Bypass
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - DST-PORT,22,DIRECT
  - RULE-SET,rule_lancidr,DIRECT,no-resolve
  - RULE-SET,rule_falsepositive,🚀 Proxy

  # Blokir Iklan & Konten Berbahaya
  - RULE-SET,rule_malicious,REJECT
  - RULE-SET,rule_maliciousip,REJECT
  - RULE-SET,rule_personalads,REJECT
  - RULE-SET,rule_basicads,REJECT
  - RULE-SET,rule_hijacking,REJECT
  - RULE-SET,rule_privacy,REJECT
  - RULE-SET,rule_porn,🚀 Proxy
  - RULE-SET,rule_nsfw,🚀 Proxy
  
  - RULE-SET,rule_Direct,DIRECT

  # Port Resmi Mihomo Core
  - DST-PORT,21-23,🚀 Proxy
  - DST-PORT,53,🚀 Proxy
  - DST-PORT,80,🚀 Proxy
  - DST-PORT,123,🚀 Proxy
  - DST-PORT,143,🚀 Proxy
  - DST-PORT,194,🚀 Proxy
  - DST-PORT,443,🚀 Proxy
  - DST-PORT,465,🚀 Proxy
  - DST-PORT,587,🚀 Proxy
  - DST-PORT,853,🚀 Proxy
  - DST-PORT,993,🚀 Proxy
  - DST-PORT,995,🚀 Proxy
  - DST-PORT,998,🚀 Proxy
  - DST-PORT,2052-2053,🚀 Proxy
  - DST-PORT,2082-2083,🚀 Proxy
  - DST-PORT,2086,🚀 Proxy
  - DST-PORT,2095-2096,🚀 Proxy
  - DST-PORT,5222,🚀 Proxy
  - DST-PORT,5228-5230,🚀 Proxy
  - DST-PORT,8080,🚀 Proxy
  - DST-PORT,8443,🚀 Proxy
  - DST-PORT,8880,🚀 Proxy
  - DST-PORT,8883,🚀 Proxy
  - DST-PORT,8888-8889,🚀 Proxy
  
  # Alokasi Grup AUTO-PING
  - RULE-SET,rule_videoconferences,⚡ Auto-Ping
  - RULE-SET,rule_discord,🚀 Proxy
  - RULE-SET,rule_Gaming,⚡ Auto-Ping
  - RULE-SET,rule_games,⚡ Auto-Ping
  - RULE-SET,rule_portgames,⚡ Auto-Ping

  # Alokasi Grup LOAD-BALANCE
  - RULE-SET,rule_playstore,🔮 Load-Balance
  - RULE-SET,rule_Streaming,🔮 Load-Balance
  - RULE-SET,rule_Youtube,🔮 Load-Balance
  - RULE-SET,rule_netflix,🔮 Load-Balance
  - RULE-SET,rule_disneyplus,🔮 Load-Balance
  - RULE-SET,rule_hbo,🔮 Load-Balance
  - RULE-SET,rule_hboasia,🔮 Load-Balance
  - RULE-SET,rule_hbohk,🔮 Load-Balance
  - RULE-SET,rule_hbousa,🔮 Load-Balance
  - RULE-SET,rule_iqiyi,🔮 Load-Balance
  - RULE-SET,rule_iqiyiinter,🔮 Load-Balance
  - RULE-SET,rule_primevideo,🔮 Load-Balance
  - RULE-SET,rule_twitch,🔮 Load-Balance
  - RULE-SET,rule_tiktok,🔮 Load-Balance

  # Alokasi Grup Utama
  - RULE-SET,rule_Sosmed,🚀 Proxy
  - RULE-SET,rule_line,🚀 Proxy
  - RULE-SET,rule_metaverse,🚀 Proxy
  - RULE-SET,rule_twitter,🚀 Proxy
  - RULE-SET,rule_telegram,🚀 Proxy
  - RULE-SET,rule_telegramcidr,🚀 Proxy
  - RULE-SET,rule_Indo,🚀 Proxy
  - RULE-SET,rule_Speedtest,🚀 Proxy

  # Sisa / Universal tambahan
  - RULE-SET,rule_umum,🚀 Proxy
  - GEOIP,LAN,DIRECT
  - MATCH,🚀 Proxy
